/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpBrowserToolsRouteImport } from './routes/api/mcp/browser-tools'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat/stream'
import { Route as ApiBrowserToolsResultRouteImport } from './routes/api/browser-tools/result'
import { Route as ApiBrowserToolsInvokeRouteImport } from './routes/api/browser-tools/invoke'
import { Route as ApiBrowserSessionEventsRouteImport } from './routes/api/browser-session/events'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpBrowserToolsRoute = ApiMcpBrowserToolsRouteImport.update({
  id: '/api/mcp/browser-tools',
  path: '/api/mcp/browser-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowserToolsResultRoute = ApiBrowserToolsResultRouteImport.update({
  id: '/api/browser-tools/result',
  path: '/api/browser-tools/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowserToolsInvokeRoute = ApiBrowserToolsInvokeRouteImport.update({
  id: '/api/browser-tools/invoke',
  path: '/api/browser-tools/invoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowserSessionEventsRoute = ApiBrowserSessionEventsRouteImport.update({
  id: '/api/browser-session/events',
  path: '/api/browser-session/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/browser-session/events': typeof ApiBrowserSessionEventsRoute
  '/api/browser-tools/invoke': typeof ApiBrowserToolsInvokeRoute
  '/api/browser-tools/result': typeof ApiBrowserToolsResultRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/mcp/browser-tools': typeof ApiMcpBrowserToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/browser-session/events': typeof ApiBrowserSessionEventsRoute
  '/api/browser-tools/invoke': typeof ApiBrowserToolsInvokeRoute
  '/api/browser-tools/result': typeof ApiBrowserToolsResultRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/mcp/browser-tools': typeof ApiMcpBrowserToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/browser-session/events': typeof ApiBrowserSessionEventsRoute
  '/api/browser-tools/invoke': typeof ApiBrowserToolsInvokeRoute
  '/api/browser-tools/result': typeof ApiBrowserToolsResultRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/mcp/browser-tools': typeof ApiMcpBrowserToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/api/browser-session/events'
    | '/api/browser-tools/invoke'
    | '/api/browser-tools/result'
    | '/api/chat/stream'
    | '/api/mcp/browser-tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/api/browser-session/events'
    | '/api/browser-tools/invoke'
    | '/api/browser-tools/result'
    | '/api/chat/stream'
    | '/api/mcp/browser-tools'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/api/browser-session/events'
    | '/api/browser-tools/invoke'
    | '/api/browser-tools/result'
    | '/api/chat/stream'
    | '/api/mcp/browser-tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ApiBrowserSessionEventsRoute: typeof ApiBrowserSessionEventsRoute
  ApiBrowserToolsInvokeRoute: typeof ApiBrowserToolsInvokeRoute
  ApiBrowserToolsResultRoute: typeof ApiBrowserToolsResultRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiMcpBrowserToolsRoute: typeof ApiMcpBrowserToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/browser-tools': {
      id: '/api/mcp/browser-tools'
      path: '/api/mcp/browser-tools'
      fullPath: '/api/mcp/browser-tools'
      preLoaderRoute: typeof ApiMcpBrowserToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browser-tools/result': {
      id: '/api/browser-tools/result'
      path: '/api/browser-tools/result'
      fullPath: '/api/browser-tools/result'
      preLoaderRoute: typeof ApiBrowserToolsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browser-tools/invoke': {
      id: '/api/browser-tools/invoke'
      path: '/api/browser-tools/invoke'
      fullPath: '/api/browser-tools/invoke'
      preLoaderRoute: typeof ApiBrowserToolsInvokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browser-session/events': {
      id: '/api/browser-session/events'
      path: '/api/browser-session/events'
      fullPath: '/api/browser-session/events'
      preLoaderRoute: typeof ApiBrowserSessionEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ApiBrowserSessionEventsRoute: ApiBrowserSessionEventsRoute,
  ApiBrowserToolsInvokeRoute: ApiBrowserToolsInvokeRoute,
  ApiBrowserToolsResultRoute: ApiBrowserToolsResultRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiMcpBrowserToolsRoute: ApiMcpBrowserToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
